//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonsai.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bonsai.Localization.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google.
        /// </summary>
        public static string AuthProvider_Google {
            get {
                return ResourceManager.GetString("AuthProvider_Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВКонтакте.
        /// </summary>
        public static string AuthProvider_Vkontakte {
            get {
                return ResourceManager.GetString("AuthProvider_Vkontakte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Яндекс.
        /// </summary>
        public static string AuthProvider_Yandex {
            get {
                return ResourceManager.GetString("AuthProvider_Yandex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес электронной почты уже зарегистрирован..
        /// </summary>
        public static string AuthService_Error_EmailAlreadyExists {
            get {
                return ResourceManager.GetString("AuthService_Error_EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения указана неверно..
        /// </summary>
        public static string AuthService_Error_InvalidBirthday {
            get {
                return ResourceManager.GetString("AuthService_Error_InvalidBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароли не совпадают..
        /// </summary>
        public static string AuthService_Error_PasswordDoesNotMatch {
            get {
                return ResourceManager.GetString("AuthService_Error_PasswordDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен содержать как минимум 6 символов..
        /// </summary>
        public static string AuthService_Error_PasswordTooShort {
            get {
                return ResourceManager.GetString("AuthService_Error_PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to День рождения.
        /// </summary>
        public static string CalendarPresenter_Birthday_Anniversary {
            get {
                return ResourceManager.GetString("CalendarPresenter_Birthday_Anniversary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения.
        /// </summary>
        public static string CalendarPresenter_Birthday_Day {
            get {
                return ResourceManager.GetString("CalendarPresenter_Birthday_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to День рождения ({0}).
        /// </summary>
        public static string CalendarPresenter_Birthday_PreciseAnniversary {
            get {
                return ResourceManager.GetString("CalendarPresenter_Birthday_PreciseAnniversary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удочерение.
        /// </summary>
        public static string CalendarPresenter_ChildAdoptionF {
            get {
                return ResourceManager.GetString("CalendarPresenter_ChildAdoptionF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Усыновление.
        /// </summary>
        public static string CalendarPresenter_ChildAdoptionM {
            get {
                return ResourceManager.GetString("CalendarPresenter_ChildAdoptionM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Годовщина смерти.
        /// </summary>
        public static string CalendarPresenter_Death_Anniversary {
            get {
                return ResourceManager.GetString("CalendarPresenter_Death_Anniversary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата смерти.
        /// </summary>
        public static string CalendarPresenter_Death_Day {
            get {
                return ResourceManager.GetString("CalendarPresenter_Death_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}-ая годовщина смерти.
        /// </summary>
        public static string CalendarPresenter_Death_PreciseAnniversary {
            get {
                return ResourceManager.GetString("CalendarPresenter_Death_PreciseAnniversary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Событие.
        /// </summary>
        public static string CalendarPresenter_Event_Title {
            get {
                return ResourceManager.GetString("CalendarPresenter_Event_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Появление питомца.
        /// </summary>
        public static string CalendarPresenter_PetAdoption_Title {
            get {
                return ResourceManager.GetString("CalendarPresenter_PetAdoption_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Годовщина .
        /// </summary>
        public static string CalendarPresenter_Wedding_Anniversary {
            get {
                return ResourceManager.GetString("CalendarPresenter_Wedding_Anniversary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to День свадьбы.
        /// </summary>
        public static string CalendarPresenter_Wedding_Day {
            get {
                return ResourceManager.GetString("CalendarPresenter_Wedding_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}-ая годовщина.
        /// </summary>
        public static string CalendarPresenter_Wedding_PreciseAnniversary {
            get {
                return ResourceManager.GetString("CalendarPresenter_Wedding_PreciseAnniversary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свадьба.
        /// </summary>
        public static string CalendarPresenter_Wedding_Title {
            get {
                return ResourceManager.GetString("CalendarPresenter_Wedding_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DatePicker_Format {
            get {
                return ResourceManager.GetString("DatePicker_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ГГГГ.ММ.ДД.
        /// </summary>
        public static string Datepicker_Placeholder {
            get {
                return ResourceManager.GetString("Datepicker_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения.
        /// </summary>
        public static string Facts_Birth_Day {
            get {
                return ResourceManager.GetString("Facts_Birth_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string Facts_Birth_DayS {
            get {
                return ResourceManager.GetString("Facts_Birth_DayS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место рождения.
        /// </summary>
        public static string Facts_Birth_Place {
            get {
                return ResourceManager.GetString("Facts_Birth_Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место.
        /// </summary>
        public static string Facts_Birth_PlaceS {
            get {
                return ResourceManager.GetString("Facts_Birth_PlaceS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место захоронения.
        /// </summary>
        public static string Facts_Death_Burial {
            get {
                return ResourceManager.GetString("Facts_Death_Burial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Захоронение.
        /// </summary>
        public static string Facts_Death_BurialS {
            get {
                return ResourceManager.GetString("Facts_Death_BurialS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Причина смерти.
        /// </summary>
        public static string Facts_Death_Cause {
            get {
                return ResourceManager.GetString("Facts_Death_Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Причина.
        /// </summary>
        public static string Facts_Death_CauseS {
            get {
                return ResourceManager.GetString("Facts_Death_CauseS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата смерти.
        /// </summary>
        public static string Facts_Death_Date {
            get {
                return ResourceManager.GetString("Facts_Death_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string Facts_Death_DateS {
            get {
                return ResourceManager.GetString("Facts_Death_DateS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место смерти.
        /// </summary>
        public static string Facts_Death_Place {
            get {
                return ResourceManager.GetString("Facts_Death_Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место.
        /// </summary>
        public static string Facts_Death_PlaceS {
            get {
                return ResourceManager.GetString("Facts_Death_PlaceS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string Facts_Event_Date {
            get {
                return ResourceManager.GetString("Facts_Event_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Биология.
        /// </summary>
        public static string Facts_Group_Bio {
            get {
                return ResourceManager.GetString("Facts_Group_Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рождение.
        /// </summary>
        public static string Facts_Group_Birth {
            get {
                return ResourceManager.GetString("Facts_Group_Birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смерть.
        /// </summary>
        public static string Facts_Group_Death {
            get {
                return ResourceManager.GetString("Facts_Group_Death", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основное.
        /// </summary>
        public static string Facts_Group_Main {
            get {
                return ResourceManager.GetString("Facts_Group_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прочее.
        /// </summary>
        public static string Facts_Group_Meta {
            get {
                return ResourceManager.GetString("Facts_Group_Meta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Личность.
        /// </summary>
        public static string Facts_Group_Person {
            get {
                return ResourceManager.GetString("Facts_Group_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        public static string Facts_Location_Address {
            get {
                return ResourceManager.GetString("Facts_Location_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приобретение.
        /// </summary>
        public static string Facts_Location_Opening {
            get {
                return ResourceManager.GetString("Facts_Location_Opening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продажа.
        /// </summary>
        public static string Facts_Location_Shutdown {
            get {
                return ResourceManager.GetString("Facts_Location_Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группа крови.
        /// </summary>
        public static string Facts_Person_BloodType {
            get {
                return ResourceManager.GetString("Facts_Person_BloodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гр. крови.
        /// </summary>
        public static string Facts_Person_BloodTypeS {
            get {
                return ResourceManager.GetString("Facts_Person_BloodTypeS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет глаз.
        /// </summary>
        public static string Facts_Person_EyeColor {
            get {
                return ResourceManager.GetString("Facts_Person_EyeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Глаза.
        /// </summary>
        public static string Facts_Person_EyeColorS {
            get {
                return ResourceManager.GetString("Facts_Person_EyeColorS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пол.
        /// </summary>
        public static string Facts_Person_Gender {
            get {
                return ResourceManager.GetString("Facts_Person_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет волос.
        /// </summary>
        public static string Facts_Person_HairColor {
            get {
                return ResourceManager.GetString("Facts_Person_HairColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Волосы.
        /// </summary>
        public static string Facts_Person_HairColorS {
            get {
                return ResourceManager.GetString("Facts_Person_HairColorS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        public static string Facts_Person_Language {
            get {
                return ResourceManager.GetString("Facts_Person_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык|Языки.
        /// </summary>
        public static string Facts_Person_LanguageS {
            get {
                return ResourceManager.GetString("Facts_Person_LanguageS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string Facts_Person_Name {
            get {
                return ResourceManager.GetString("Facts_Person_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя|Имена.
        /// </summary>
        public static string Facts_Person_NameS {
            get {
                return ResourceManager.GetString("Facts_Person_NameS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профессия.
        /// </summary>
        public static string Facts_Person_Profession {
            get {
                return ResourceManager.GetString("Facts_Person_Profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профессия|Профессии.
        /// </summary>
        public static string Facts_Person_ProfessionS {
            get {
                return ResourceManager.GetString("Facts_Person_ProfessionS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Религия.
        /// </summary>
        public static string Facts_Person_Religion {
            get {
                return ResourceManager.GetString("Facts_Person_Religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Религия|Религии.
        /// </summary>
        public static string Facts_Person_ReligionS {
            get {
                return ResourceManager.GetString("Facts_Person_ReligionS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хобби.
        /// </summary>
        public static string Facts_Person_Skill {
            get {
                return ResourceManager.GetString("Facts_Person_Skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакты.
        /// </summary>
        public static string Facts_Person_SocialProfiles {
            get {
                return ResourceManager.GetString("Facts_Person_SocialProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порода.
        /// </summary>
        public static string Facts_Pet_Breed {
            get {
                return ResourceManager.GetString("Facts_Pet_Breed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Окрас.
        /// </summary>
        public static string Facts_Pet_Color {
            get {
                return ResourceManager.GetString("Facts_Pet_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пол.
        /// </summary>
        public static string Facts_Pet_Gender {
            get {
                return ResourceManager.GetString("Facts_Pet_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string Facts_Pet_Name {
            get {
                return ResourceManager.GetString("Facts_Pet_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид.
        /// </summary>
        public static string Facts_Pet_Species {
            get {
                return ResourceManager.GetString("Facts_Pet_Species", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось авторизоваться через выбранного провайдера.&lt;br/&gt;Попробуйте еще раз, или обратитесь к администратору Bonsai..
        /// </summary>
        public static string Front_AuthFailed_Description {
            get {
                return ResourceManager.GetString("Front_AuthFailed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад на страницу авторизации.
        /// </summary>
        public static string Front_AuthFailed_GoBack {
            get {
                return ResourceManager.GetString("Front_AuthFailed_GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка авторизации.
        /// </summary>
        public static string Front_AuthFailed_Title {
            get {
                return ResourceManager.GetString("Front_AuthFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В этот день ничего не произошло..
        /// </summary>
        public static string Front_Calendar_NothingHappened {
            get {
                return ResourceManager.GetString("Front_Calendar_NothingHappened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пн, Вт, Ср, Чт, Пт, Сб, Вс.
        /// </summary>
        public static string Front_Calendar_WeekdaysShort {
            get {
                return ResourceManager.GetString("Front_Calendar_WeekdaysShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить страницу.
        /// </summary>
        public static string Front_Error_NotFound_AddPage {
            get {
                return ResourceManager.GetString("Front_Error_NotFound_AddPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увы и ах! Такая страница не существует. &lt;br/&gt;Возможно, она еще не создана, или вы перешли по ссылке с ошибкой..
        /// </summary>
        public static string Front_Error_NotFound_Description {
            get {
                return ResourceManager.GetString("Front_Error_NotFound_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка 404.
        /// </summary>
        public static string Front_Error_NotFound_Error {
            get {
                return ResourceManager.GetString("Front_Error_NotFound_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На главную.
        /// </summary>
        public static string Front_Error_NotFound_MainLink {
            get {
                return ResourceManager.GetString("Front_Error_NotFound_MainLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница не найдена.
        /// </summary>
        public static string Front_Error_NotFound_Title {
            get {
                return ResourceManager.GetString("Front_Error_NotFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестно.
        /// </summary>
        public static string Front_Facts_DeathDate_Unknown {
            get {
                return ResourceManager.GetString("Front_Facts_DeathDate_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Женский.
        /// </summary>
        public static string Front_Facts_Gender_Female {
            get {
                return ResourceManager.GetString("Front_Facts_Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мужской.
        /// </summary>
        public static string Front_Facts_Gender_Male {
            get {
                return ResourceManager.GetString("Front_Facts_Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2} {0} {1}.
        /// </summary>
        public static string Front_Facts_HumanName_FullFormat {
            get {
                return ResourceManager.GetString("Front_Facts_HumanName_FullFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилии.
        /// </summary>
        public static string Front_Facts_HumanName_LastNames {
            get {
                return ResourceManager.GetString("Front_Facts_HumanName_LastNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная страница.
        /// </summary>
        public static string Front_Home_Title {
            get {
                return ResourceManager.GetString("Front_Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новые медиа-файлы.
        /// </summary>
        public static string Front_Home_UpdatedMedia {
            get {
                return ResourceManager.GetString("Front_Home_UpdatedMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновленные страницы.
        /// </summary>
        public static string Front_Home_UpdatedPages {
            get {
                return ResourceManager.GetString("Front_Home_UpdatedPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При загрузке Bonsai произошла ошибка.&lt;br/&gt;Подробная информация записана в логи..
        /// </summary>
        public static string Front_Loading_Error {
            get {
                return ResourceManager.GetString("Front_Loading_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonsai загружается....
        /// </summary>
        public static string Front_Loading_InProgress1 {
            get {
                return ResourceManager.GetString("Front_Loading_InProgress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Откиньтесь на спинку кресла и отдохните - это займет не более минуты :).
        /// </summary>
        public static string Front_Loading_InProgress2 {
            get {
                return ResourceManager.GetString("Front_Loading_InProgress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка.
        /// </summary>
        public static string Front_Loading_Title {
            get {
                return ResourceManager.GetString("Front_Loading_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Демонстрационный аккаунт администратора:.
        /// </summary>
        public static string Front_Login_DemoAccount {
            get {
                return ResourceManager.GetString("Front_Login_DemoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Или введите логин и пароль, полученные от администратора:.
        /// </summary>
        public static string Front_Login_EnterPassword {
            get {
                return ResourceManager.GetString("Front_Login_EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход через {0}.
        /// </summary>
        public static string Front_Login_ExternalAuth {
            get {
                return ResourceManager.GetString("Front_Login_ExternalAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string Front_Login_Login {
            get {
                return ResourceManager.GetString("Front_Login_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница доступна только для зарегистрированных пользователей..
        /// </summary>
        public static string Front_Login_OnlyForRegistered {
            get {
                return ResourceManager.GetString("Front_Login_OnlyForRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Front_Login_Password {
            get {
                return ResourceManager.GetString("Front_Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход по логину и паролю.
        /// </summary>
        public static string Front_Login_PasswordAuth {
            get {
                return ResourceManager.GetString("Front_Login_PasswordAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, авторизуйтесь с помощью одного из доступных сервисов:.
        /// </summary>
        public static string Front_Login_PleaseAuthorize {
            get {
                return ResourceManager.GetString("Front_Login_PleaseAuthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы также можете &lt;a href=&quot;{0}&quot;&gt;зарегистрировать новую запись&lt;/a&gt;, или ввести логин и пароль, полученные от администратора:.
        /// </summary>
        public static string Front_Login_Register {
            get {
                return ResourceManager.GetString("Front_Login_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Ошибка:&lt;/b&gt; Не удалось авторизоваться.&lt;br /&gt;Возможно, вы ввели некорректный пароль? Попробуйте снова..
        /// </summary>
        public static string Front_Login_StatusFailed {
            get {
                return ResourceManager.GetString("Front_Login_StatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Ошибка:&lt;/b&gt;Ваша учетная запись заблокирована..
        /// </summary>
        public static string Front_Login_StatusLockedOut {
            get {
                return ResourceManager.GetString("Front_Login_StatusLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша учетная запись еще не была проверена администратором.&lt;br/&gt;Пожалуйста, дождитесь проверки - тогда вы сможете пользоваться системой..
        /// </summary>
        public static string Front_Login_StatusUnvalidated {
            get {
                return ResourceManager.GetString("Front_Login_StatusUnvalidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизация.
        /// </summary>
        public static string Front_Login_Title {
            get {
                return ResourceManager.GetString("Front_Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        public static string Front_Login_Username {
            get {
                return ResourceManager.GetString("Front_Login_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действия.
        /// </summary>
        public static string Front_Media_Actions {
            get {
                return ResourceManager.GetString("Front_Media_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string Front_Media_Date {
            get {
                return ResourceManager.GetString("Front_Media_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображены.
        /// </summary>
        public static string Front_Media_Depicted {
            get {
                return ResourceManager.GetString("Front_Media_Depicted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скачать.
        /// </summary>
        public static string Front_Media_Download {
            get {
                return ResourceManager.GetString("Front_Media_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string Front_Media_Edit {
            get {
                return ResourceManager.GetString("Front_Media_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Событие.
        /// </summary>
        public static string Front_Media_Event {
            get {
                return ResourceManager.GetString("Front_Media_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место.
        /// </summary>
        public static string Front_Media_Location {
            get {
                return ResourceManager.GetString("Front_Media_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оригинал.
        /// </summary>
        public static string Front_Media_Original {
            get {
                return ResourceManager.GetString("Front_Media_Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш браузер не поддерживает просмотр видео..
        /// </summary>
        public static string Front_Media_Video_BrowserUnsupported {
            get {
                return ResourceManager.GetString("Front_Media_Video_BrowserUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видео обрабатывается....
        /// </summary>
        public static string Front_Media_Video_Processing {
            get {
                return ResourceManager.GetString("Front_Media_Video_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видео будет доступно после обработки. Попробуйте перезагрузить страницу..
        /// </summary>
        public static string Front_Media_Video_TryRefreshing {
            get {
                return ResourceManager.GetString("Front_Media_Video_TryRefreshing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правки.
        /// </summary>
        public static string Front_Page_AdminLinks_Changes {
            get {
                return ResourceManager.GetString("Front_Page_AdminLinks_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Медиа.
        /// </summary>
        public static string Front_Page_AdminLinks_Media {
            get {
                return ResourceManager.GetString("Front_Page_AdminLinks_Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Связи.
        /// </summary>
        public static string Front_Page_AdminLinks_Relations {
            get {
                return ResourceManager.GetString("Front_Page_AdminLinks_Relations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст и факты.
        /// </summary>
        public static string Front_Page_AdminLinks_TextAndFacts {
            get {
                return ResourceManager.GetString("Front_Page_AdminLinks_TextAndFacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ничего не известно..
        /// </summary>
        public static string Front_Page_Description_Empty {
            get {
                return ResourceManager.GetString("Front_Page_Description_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата неизвестна.
        /// </summary>
        public static string Front_Page_Media_DateUnknown {
            get {
                return ResourceManager.GetString("Front_Page_Media_DateUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Медиа-файлов нет..
        /// </summary>
        public static string Front_Page_Media_Empty {
            get {
                return ResourceManager.GetString("Front_Page_Media_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Давно.
        /// </summary>
        public static string Front_Page_Media_LongAgo {
            get {
                return ResourceManager.GetString("Front_Page_Media_LongAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  — Медиа.
        /// </summary>
        public static string Front_Page_Media_Title {
            get {
                return ResourceManager.GetString("Front_Page_Media_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылок на данную страницу нет..
        /// </summary>
        public static string Front_Page_References_Empty {
            get {
                return ResourceManager.GetString("Front_Page_References_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На данную страницу ссылаются следующие страницы:.
        /// </summary>
        public static string Front_Page_References_Hint {
            get {
                return ResourceManager.GetString("Front_Page_References_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Front_Page_Tabs_Description {
            get {
                return ResourceManager.GetString("Front_Page_Tabs_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Медиа.
        /// </summary>
        public static string Front_Page_Tabs_Media {
            get {
                return ResourceManager.GetString("Front_Page_Tabs_Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылки.
        /// </summary>
        public static string Front_Page_Tabs_References {
            get {
                return ResourceManager.GetString("Front_Page_Tabs_References", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дерево.
        /// </summary>
        public static string Front_Page_Tabs_Tree {
            get {
                return ResourceManager.GetString("Front_Page_Tabs_Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во весь экран.
        /// </summary>
        public static string Front_Page_Tree_Fullscreen {
            get {
                return ResourceManager.GetString("Front_Page_Tree_Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В новом окне.
        /// </summary>
        public static string Front_Page_Tree_NewWindow {
            get {
                return ResourceManager.GetString("Front_Page_Tree_NewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} — Фамильное древо.
        /// </summary>
        public static string Front_Page_Tree_Title {
            get {
                return ResourceManager.GetString("Front_Page_Tree_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения.
        /// </summary>
        public static string Front_Register_Birthday {
            get {
                return ResourceManager.GetString("Front_Register_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать личную страницу.
        /// </summary>
        public static string Front_Register_CreatePersonalPage {
            get {
                return ResourceManager.GetString("Front_Register_CreatePersonalPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Front_Register_Email {
            get {
                return ResourceManager.GetString("Front_Register_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будет использоваться в качестве логина.
        /// </summary>
        public static string Front_Register_Email_Hint {
            get {
                return ResourceManager.GetString("Front_Register_Email_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Ошибка:&lt;/b&gt; пожалуйста, убедитесь, что вы заполнили все поля корректно и попробуйте снова..
        /// </summary>
        public static string Front_Register_Error {
            get {
                return ResourceManager.GetString("Front_Register_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string Front_Register_FirstName {
            get {
                return ResourceManager.GetString("Front_Register_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша учетная запись получит права администратора..
        /// </summary>
        public static string Front_Register_FirstUserHint {
            get {
                return ResourceManager.GetString("Front_Register_FirstUserHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверьте, что ввели актуальные данные - на русском языке и без ошибок. &lt;br/&gt;Учетная запись будет проверена администратором, после чего вы сможете авторизоваться и пользоваться системой..
        /// </summary>
        public static string Front_Register_Hint {
            get {
                return ResourceManager.GetString("Front_Register_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string Front_Register_LastName {
            get {
                return ResourceManager.GetString("Front_Register_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество.
        /// </summary>
        public static string Front_Register_MiddleName {
            get {
                return ResourceManager.GetString("Front_Register_MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опции.
        /// </summary>
        public static string Front_Register_Options {
            get {
                return ResourceManager.GetString("Front_Register_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Front_Register_Password {
            get {
                return ResourceManager.GetString("Front_Register_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимум 6 символов.
        /// </summary>
        public static string Front_Register_Password_Hint {
            get {
                return ResourceManager.GetString("Front_Register_Password_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повтор пароля.
        /// </summary>
        public static string Front_Register_Password_Repeat {
            get {
                return ResourceManager.GetString("Front_Register_Password_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Front_Register_Submit {
            get {
                return ResourceManager.GetString("Front_Register_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для создания учетной записи, пожалуйста, введите необходимую информацию..
        /// </summary>
        public static string Front_Register_Subtitle {
            get {
                return ResourceManager.GetString("Front_Register_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Front_Register_Title {
            get {
                return ResourceManager.GetString("Front_Register_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите дату вашего рождения..
        /// </summary>
        public static string Front_Register_Validation_BirthdayEmpty {
            get {
                return ResourceManager.GetString("Front_Register_Validation_BirthdayEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите дату в формате ГГГГ.ММ.ДД..
        /// </summary>
        public static string Front_Register_Validation_BirthdayInvalid {
            get {
                return ResourceManager.GetString("Front_Register_Validation_BirthdayInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите адрес электронной почты..
        /// </summary>
        public static string Front_Register_Validation_EmailEmpty {
            get {
                return ResourceManager.GetString("Front_Register_Validation_EmailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите валидный адрес электронной почты..
        /// </summary>
        public static string Front_Register_Validation_EmailInvalid {
            get {
                return ResourceManager.GetString("Front_Register_Validation_EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите ваше имя..
        /// </summary>
        public static string Front_Register_Validation_FirstNameEmpty {
            get {
                return ResourceManager.GetString("Front_Register_Validation_FirstNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите вашу фамилию..
        /// </summary>
        public static string Front_Register_Validation_LastNameEmpty {
            get {
                return ResourceManager.GetString("Front_Register_Validation_LastNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учетная запись не может быть создана, потому что регистрация новых пользователей запрещена администратором..
        /// </summary>
        public static string Front_RegisterDisabled_Description {
            get {
                return ResourceManager.GetString("Front_RegisterDisabled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация отклонена.
        /// </summary>
        public static string Front_RegisterDisabled_Title {
            get {
                return ResourceManager.GetString("Front_RegisterDisabled_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На главную страницу.
        /// </summary>
        public static string Front_RegisterSuccess_GoMain {
            get {
                return ResourceManager.GetString("Front_RegisterSuccess_GoMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша учетная запись будет проверена администратором, после чего вы сможете авторизоваться и пользоваться системой..
        /// </summary>
        public static string Front_RegisterSuccess_ReviewPending {
            get {
                return ResourceManager.GetString("Front_RegisterSuccess_ReviewPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы успешно зарегистрированы!.
        /// </summary>
        public static string Front_RegisterSuccess_Success {
            get {
                return ResourceManager.GetString("Front_RegisterSuccess_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Front_RegisterSuccess_Title {
            get {
                return ResourceManager.GetString("Front_RegisterSuccess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По вашему запросу ничего не найдено..
        /// </summary>
        public static string Front_Search_NothingFound {
            get {
                return ResourceManager.GetString("Front_Search_NothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск….
        /// </summary>
        public static string Front_Search_Placeholder {
            get {
                return ResourceManager.GetString("Front_Search_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрос слишком короткий. Введите как минимум три символа..
        /// </summary>
        public static string Front_Search_QueryTooShort {
            get {
                return ResourceManager.GetString("Front_Search_QueryTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результаты поиска.
        /// </summary>
        public static string Front_Search_Results {
            get {
                return ResourceManager.GetString("Front_Search_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        public static string Front_Search_Title {
            get {
                return ResourceManager.GetString("Front_Search_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить дерево..
        /// </summary>
        public static string Front_Tree_LoadFailed {
            get {
                return ResourceManager.GetString("Front_Tree_LoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка....
        /// </summary>
        public static string Front_Tree_Loading {
            get {
                return ResourceManager.GetString("Front_Tree_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} — Фамильное древо.
        /// </summary>
        public static string Front_Tree_Title {
            get {
                return ResourceManager.GetString("Front_Tree_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string FuzzyDate_Age_FullPreciseFormat {
            get {
                return ResourceManager.GetString("FuzzyDate_Age_FullPreciseFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}..{1} {2}.
        /// </summary>
        public static string FuzzyDate_Age_FullRangeFormat {
            get {
                return ResourceManager.GetString("FuzzyDate_Age_FullRangeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меньше месяца.
        /// </summary>
        public static string FuzzyDate_Age_LessThanAMonth {
            get {
                return ResourceManager.GetString("FuzzyDate_Age_LessThanAMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меньше года.
        /// </summary>
        public static string FuzzyDate_Age_LessThanAYear {
            get {
                return ResourceManager.GetString("FuzzyDate_Age_LessThanAYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string FuzzyDate_Age_MonthsFormat {
            get {
                return ResourceManager.GetString("FuzzyDate_Age_MonthsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string FuzzyDate_Age_YearsFormat {
            get {
                return ResourceManager.GetString("FuzzyDate_Age_YearsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to апрель.
        /// </summary>
        public static string FuzzyDate_April {
            get {
                return ResourceManager.GetString("FuzzyDate_April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} апреля.
        /// </summary>
        public static string FuzzyDate_AprilPrecise {
            get {
                return ResourceManager.GetString("FuzzyDate_AprilPrecise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to август.
        /// </summary>
        public static string FuzzyDate_August {
            get {
                return ResourceManager.GetString("FuzzyDate_August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} августа.
        /// </summary>
        public static string FuzzyDate_AugustPrecise {
            get {
                return ResourceManager.GetString("FuzzyDate_AugustPrecise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}-е.
        /// </summary>
        public static string FuzzyDate_DecadeFormat {
            get {
                return ResourceManager.GetString("FuzzyDate_DecadeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to декабрь.
        /// </summary>
        public static string FuzzyDate_December {
            get {
                return ResourceManager.GetString("FuzzyDate_December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} декабря.
        /// </summary>
        public static string FuzzyDate_DecemberPrecise {
            get {
                return ResourceManager.GetString("FuzzyDate_DecemberPrecise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to февраль.
        /// </summary>
        public static string FuzzyDate_February {
            get {
                return ResourceManager.GetString("FuzzyDate_February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} февраля.
        /// </summary>
        public static string FuzzyDate_FebruaryPrecise {
            get {
                return ResourceManager.GetString("FuzzyDate_FebruaryPrecise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}-е.
        /// </summary>
        public static string FuzzyDate_FullDecadeFormat {
            get {
                return ResourceManager.GetString("FuzzyDate_FullDecadeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string FuzzyDate_FullYearFormat {
            get {
                return ResourceManager.GetString("FuzzyDate_FullYearFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to январь.
        /// </summary>
        public static string FuzzyDate_January {
            get {
                return ResourceManager.GetString("FuzzyDate_January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} января.
        /// </summary>
        public static string FuzzyDate_JanuaryPrecise {
            get {
                return ResourceManager.GetString("FuzzyDate_JanuaryPrecise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to июль.
        /// </summary>
        public static string FuzzyDate_July {
            get {
                return ResourceManager.GetString("FuzzyDate_July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} июля.
        /// </summary>
        public static string FuzzyDate_JulyPrecise {
            get {
                return ResourceManager.GetString("FuzzyDate_JulyPrecise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to июнь.
        /// </summary>
        public static string FuzzyDate_June {
            get {
                return ResourceManager.GetString("FuzzyDate_June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} июня.
        /// </summary>
        public static string FuzzyDate_JunePrecise {
            get {
                return ResourceManager.GetString("FuzzyDate_JunePrecise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to март.
        /// </summary>
        public static string FuzzyDate_March {
            get {
                return ResourceManager.GetString("FuzzyDate_March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} марта.
        /// </summary>
        public static string FuzzyDate_MarchPrecise {
            get {
                return ResourceManager.GetString("FuzzyDate_MarchPrecise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to май.
        /// </summary>
        public static string FuzzyDate_May {
            get {
                return ResourceManager.GetString("FuzzyDate_May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} мая.
        /// </summary>
        public static string FuzzyDate_MayPrecise {
            get {
                return ResourceManager.GetString("FuzzyDate_MayPrecise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to месяц|месяца|месяцев.
        /// </summary>
        public static string FuzzyDate_Months {
            get {
                return ResourceManager.GetString("FuzzyDate_Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ноябрь.
        /// </summary>
        public static string FuzzyDate_November {
            get {
                return ResourceManager.GetString("FuzzyDate_November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ноября.
        /// </summary>
        public static string FuzzyDate_NovemberPrecise {
            get {
                return ResourceManager.GetString("FuzzyDate_NovemberPrecise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to октябрь.
        /// </summary>
        public static string FuzzyDate_October {
            get {
                return ResourceManager.GetString("FuzzyDate_October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} октября.
        /// </summary>
        public static string FuzzyDate_OctoberPrecise {
            get {
                return ResourceManager.GetString("FuzzyDate_OctoberPrecise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сентябрь.
        /// </summary>
        public static string FuzzyDate_September {
            get {
                return ResourceManager.GetString("FuzzyDate_September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} сентября.
        /// </summary>
        public static string FuzzyDate_SeptemberPrecise {
            get {
                return ResourceManager.GetString("FuzzyDate_SeptemberPrecise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string FuzzyDate_YearFormat {
            get {
                return ResourceManager.GetString("FuzzyDate_YearFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to год|года|лет.
        /// </summary>
        public static string FuzzyDate_Years {
            get {
                return ResourceManager.GetString("FuzzyDate_Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница не найдена..
        /// </summary>
        public static string Global_Error_PageNotFound {
            get {
                return ResourceManager.GetString("Global_Error_PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь не найден..
        /// </summary>
        public static string Global_Error_UserNotFound {
            get {
                return ResourceManager.GetString("Global_Error_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление.
        /// </summary>
        public static string Global_UserHeader_Administration {
            get {
                return ResourceManager.GetString("Global_UserHeader_Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string Global_UserHeader_Login {
            get {
                return ResourceManager.GetString("Global_UserHeader_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        public static string Global_UserHeader_Logout {
            get {
                return ResourceManager.GetString("Global_UserHeader_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница.
        /// </summary>
        public static string Global_UserHeader_Page {
            get {
                return ResourceManager.GetString("Global_UserHeader_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите запрос для поиска.
        /// </summary>
        public static string Js_Autocomplete_Empty {
            get {
                return ResourceManager.GetString("Js_Autocomplete_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ничего не найдено.
        /// </summary>
        public static string Js_Autocomplete_NothingFound {
            get {
                return ResourceManager.GetString("Js_Autocomplete_NothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недопустимая дата..
        /// </summary>
        public static string Js_Datepicker_InvalidDate {
            get {
                return ResourceManager.GetString("Js_Datepicker_InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ru-ru.
        /// </summary>
        public static string Js_Datepicker_Locale {
            get {
                return ResourceManager.GetString("Js_Datepicker_Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ru-RU.
        /// </summary>
        public static string Js_Draft_DateLocale {
            get {
                return ResourceManager.GetString("Js_Draft_DateLocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все изменения для данной страницы будут сброшены.\n\nВы уверены?.
        /// </summary>
        public static string Js_Draft_DiscardConfirmation {
            get {
                return ResourceManager.GetString("Js_Draft_DiscardConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Черновик сохранен в {0}..
        /// </summary>
        public static string Js_Draft_SavedAt {
            get {
                return ResourceManager.GetString("Js_Draft_SavedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        public static string Js_Facts_DefaultLanguage {
            get {
                return ResourceManager.GetString("Js_Facts_DefaultLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +79251234567.
        /// </summary>
        public static string Js_Facts_PhoneNumberPlaceholder {
            get {
                return ResourceManager.GetString("Js_Facts_PhoneNumberPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Js_Markdown_Description {
            get {
                return ResourceManager.GetString("Js_Markdown_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справка по форматированию.
        /// </summary>
        public static string Js_Markdown_FormatReference {
            get {
                return ResourceManager.GetString("Js_Markdown_FormatReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать медиа-файл.
        /// </summary>
        public static string Js_Markdown_PickMedia {
            get {
                return ResourceManager.GetString("Js_Markdown_PickMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать страницу.
        /// </summary>
        public static string Js_Markdown_PickPage {
            get {
                return ResourceManager.GetString("Js_Markdown_PickPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        public static string Js_MediaPopup_Close {
            get {
                return ResourceManager.GetString("Js_MediaPopup_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %curr% из %total%.
        /// </summary>
        public static string Js_MediaPopup_CounterTemplate {
            get {
                return ResourceManager.GetString("Js_MediaPopup_CounterTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить данные..
        /// </summary>
        public static string Js_MediaPopup_LoadFailed {
            get {
                return ResourceManager.GetString("Js_MediaPopup_LoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница или имя.
        /// </summary>
        public static string Js_PagePicker_PageOrName {
            get {
                return ResourceManager.GetString("Js_PagePicker_PageOrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (без ссылки).
        /// </summary>
        public static string Js_PagePicker_WithoutLink {
            get {
                return ResourceManager.GetString("Js_PagePicker_WithoutLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить изображение!.
        /// </summary>
        public static string Js_Photo_UploadFailed {
            get {
                return ResourceManager.GetString("Js_Photo_UploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить медиа-файлы.
        /// </summary>
        public static string Js_Picker_MediaLoadFailed {
            get {
                return ResourceManager.GetString("Js_Picker_MediaLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить страницы.
        /// </summary>
        public static string Js_Picker_PageLoadFailed {
            get {
                return ResourceManager.GetString("Js_Picker_PageLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите название страницы.
        /// </summary>
        public static string Js_Relations_EnterPageTitle {
            get {
                return ResourceManager.GetString("Js_Relations_EnterPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница или название.
        /// </summary>
        public static string Js_Tags_PageOrTitle {
            get {
                return ResourceManager.GetString("Js_Tags_PageOrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл слишком большой!.
        /// </summary>
        public static string Js_Upload_FileTooBig {
            get {
                return ResourceManager.GetString("Js_Upload_FileTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестная ошибка.
        /// </summary>
        public static string Js_Upload_UnknownError {
            get {
                return ResourceManager.GetString("Js_Upload_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите имя.
        /// </summary>
        public static string Js_User_EnterName {
            get {
                return ResourceManager.GetString("Js_User_EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расположение указано более одного раза..
        /// </summary>
        public static string MarkdownService_AlignmentAmbiguous {
            get {
                return ResourceManager.GetString("MarkdownService_AlignmentAmbiguous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестное расположение медиа-файла..
        /// </summary>
        public static string MarkdownService_AlignmentUnknown {
            get {
                return ResourceManager.GetString("MarkdownService_AlignmentUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание указано более одного раза..
        /// </summary>
        public static string MarkdownService_DescriptionAmbiguous {
            get {
                return ResourceManager.GetString("MarkdownService_DescriptionAmbiguous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Медиа-файл {0} не найден..
        /// </summary>
        public static string MarkdownService_MediaNotFound {
            get {
                return ResourceManager.GetString("MarkdownService_MediaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница не найдена: {0}..
        /// </summary>
        public static string MarkdownService_PageNotFound {
            get {
                return ResourceManager.GetString("MarkdownService_PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер указан более одного раза..
        /// </summary>
        public static string MarkdownService_SizeAmbiguous {
            get {
                return ResourceManager.GetString("MarkdownService_SizeAmbiguous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестный размер медиа-файла..
        /// </summary>
        public static string MarkdownService_SizeUnknown {
            get {
                return ResourceManager.GetString("MarkdownService_SizeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внук|Внучка|Внук.
        /// </summary>
        public static string Relations_ChildChild {
            get {
                return ResourceManager.GetString("Relations_ChildChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внуки.
        /// </summary>
        public static string Relations_ChildChild_Mult {
            get {
                return ResourceManager.GetString("Relations_ChildChild_Mult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зять.
        /// </summary>
        public static string Relations_ChildFSpouseM {
            get {
                return ResourceManager.GetString("Relations_ChildFSpouseM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зяти.
        /// </summary>
        public static string Relations_ChildFSpouseM_Mult {
            get {
                return ResourceManager.GetString("Relations_ChildFSpouseM_Mult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невестка.
        /// </summary>
        public static string Relations_ChildMSpouseF {
            get {
                return ResourceManager.GetString("Relations_ChildMSpouseF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невестки.
        /// </summary>
        public static string Relations_ChildMSpouseF_Mult {
            get {
                return ResourceManager.GetString("Relations_ChildMSpouseF_Mult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коллега.
        /// </summary>
        public static string Relations_Colleague {
            get {
                return ResourceManager.GetString("Relations_Colleague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коллеги.
        /// </summary>
        public static string Relations_Colleague_Mult {
            get {
                return ResourceManager.GetString("Relations_Colleague_Mult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Событие.
        /// </summary>
        public static string Relations_Event {
            get {
                return ResourceManager.GetString("Relations_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to События.
        /// </summary>
        public static string Relations_Event_Mult {
            get {
                return ResourceManager.GetString("Relations_Event_Mult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участник|Участница|Участник.
        /// </summary>
        public static string Relations_EventVisitor {
            get {
                return ResourceManager.GetString("Relations_EventVisitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участники.
        /// </summary>
        public static string Relations_EventVisitor_Mult {
            get {
                return ResourceManager.GetString("Relations_EventVisitor_Mult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Друг|Подруга|Друг.
        /// </summary>
        public static string Relations_Friend {
            get {
                return ResourceManager.GetString("Relations_Friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Друзья.
        /// </summary>
        public static string Relations_Friend_Mult {
            get {
                return ResourceManager.GetString("Relations_Friend_Mult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страницы.
        /// </summary>
        public static string Relations_Group_Pages {
            get {
                return ResourceManager.GetString("Relations_Group_Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Люди.
        /// </summary>
        public static string Relations_Group_People {
            get {
                return ResourceManager.GetString("Relations_Group_People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Родственники.
        /// </summary>
        public static string Relations_Group_Relatives {
            get {
                return ResourceManager.GetString("Relations_Group_Relatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место.
        /// </summary>
        public static string Relations_Location {
            get {
                return ResourceManager.GetString("Relations_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Места.
        /// </summary>
        public static string Relations_Location_Mult {
            get {
                return ResourceManager.GetString("Relations_Location_Mult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Житель|Жительница|Житель.
        /// </summary>
        public static string Relations_LocationInhabitant {
            get {
                return ResourceManager.GetString("Relations_LocationInhabitant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жители.
        /// </summary>
        public static string Relations_LocationInhabitant_Mult {
            get {
                return ResourceManager.GetString("Relations_LocationInhabitant_Mult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Владелец|Владелица|Владелец.
        /// </summary>
        public static string Relations_Owner {
            get {
                return ResourceManager.GetString("Relations_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Владельцы.
        /// </summary>
        public static string Relations_Owner_Mult {
            get {
                return ResourceManager.GetString("Relations_Owner_Mult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Родитель.
        /// </summary>
        public static string Relations_Parent {
            get {
                return ResourceManager.GetString("Relations_Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Родители.
        /// </summary>
        public static string Relations_Parent_Mult {
            get {
                return ResourceManager.GetString("Relations_Parent_Mult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сестра.
        /// </summary>
        public static string Relations_ParentChildF {
            get {
                return ResourceManager.GetString("Relations_ParentChildF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сестры.
        /// </summary>
        public static string Relations_ParentChildF_Mult {
            get {
                return ResourceManager.GetString("Relations_ParentChildF_Mult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брат.
        /// </summary>
        public static string Relations_ParentChildM {
            get {
                return ResourceManager.GetString("Relations_ParentChildM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Братья.
        /// </summary>
        public static string Relations_ParentChildM_Mult {
            get {
                return ResourceManager.GetString("Relations_ParentChildM_Mult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мать.
        /// </summary>
        public static string Relations_ParentF {
            get {
                return ResourceManager.GetString("Relations_ParentF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отец.
        /// </summary>
        public static string Relations_ParentM {
            get {
                return ResourceManager.GetString("Relations_ParentM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бабушка.
        /// </summary>
        public static string Relations_ParentParentF {
            get {
                return ResourceManager.GetString("Relations_ParentParentF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бабушки.
        /// </summary>
        public static string Relations_ParentParentF_Mult {
            get {
                return ResourceManager.GetString("Relations_ParentParentF_Mult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дедушка.
        /// </summary>
        public static string Relations_ParentParentM {
            get {
                return ResourceManager.GetString("Relations_ParentParentM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дедушки.
        /// </summary>
        public static string Relations_ParentParentM_Mult {
            get {
                return ResourceManager.GetString("Relations_ParentParentM_Mult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Питомец.
        /// </summary>
        public static string Relations_Pet {
            get {
                return ResourceManager.GetString("Relations_Pet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Питомцы.
        /// </summary>
        public static string Relations_Pet_Mult {
            get {
                return ResourceManager.GetString("Relations_Pet_Mult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сын|Дочь|Ребенок.
        /// </summary>
        public static string Relations_SpouseChild {
            get {
                return ResourceManager.GetString("Relations_SpouseChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дети.
        /// </summary>
        public static string Relations_SpouseChild_Mult {
            get {
                return ResourceManager.GetString("Relations_SpouseChild_Mult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жена.
        /// </summary>
        public static string Relations_SpouseF {
            get {
                return ResourceManager.GetString("Relations_SpouseF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свояченица.
        /// </summary>
        public static string Relations_SpouseFParentChildF {
            get {
                return ResourceManager.GetString("Relations_SpouseFParentChildF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свояченицы.
        /// </summary>
        public static string Relations_SpouseFParentChildF_Mult {
            get {
                return ResourceManager.GetString("Relations_SpouseFParentChildF_Mult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шурин.
        /// </summary>
        public static string Relations_SpouseFParentChildM {
            get {
                return ResourceManager.GetString("Relations_SpouseFParentChildM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шурины.
        /// </summary>
        public static string Relations_SpouseFParentChildM_Mult {
            get {
                return ResourceManager.GetString("Relations_SpouseFParentChildM_Mult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Теща.
        /// </summary>
        public static string Relations_SpouseFParentF {
            get {
                return ResourceManager.GetString("Relations_SpouseFParentF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тесть.
        /// </summary>
        public static string Relations_SpouseFParentM {
            get {
                return ResourceManager.GetString("Relations_SpouseFParentM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Муж.
        /// </summary>
        public static string Relations_SpouseM {
            get {
                return ResourceManager.GetString("Relations_SpouseM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Золовка.
        /// </summary>
        public static string Relations_SpouseMParentChildF {
            get {
                return ResourceManager.GetString("Relations_SpouseMParentChildF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Золовки.
        /// </summary>
        public static string Relations_SpouseMParentChildF_Mult {
            get {
                return ResourceManager.GetString("Relations_SpouseMParentChildF_Mult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деверь.
        /// </summary>
        public static string Relations_SpouseMParentChildM {
            get {
                return ResourceManager.GetString("Relations_SpouseMParentChildM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Девери.
        /// </summary>
        public static string Relations_SpouseMParentChildM_Mult {
            get {
                return ResourceManager.GetString("Relations_SpouseMParentChildM_Mult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свекровь.
        /// </summary>
        public static string Relations_SpouseMParentF {
            get {
                return ResourceManager.GetString("Relations_SpouseMParentF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свекр.
        /// </summary>
        public static string Relations_SpouseMParentM {
            get {
                return ResourceManager.GetString("Relations_SpouseMParentM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сын|Дочь|Ребенок.
        /// </summary>
        public static string Relations_SpouseOtherChild {
            get {
                return ResourceManager.GetString("Relations_SpouseOtherChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дети.
        /// </summary>
        public static string Relations_SpouseOtherChild_Mult {
            get {
                return ResourceManager.GetString("Relations_SpouseOtherChild_Mult", resourceCulture);
            }
        }
    }
}
