//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonsai.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bonsai.Localization.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DatePicker_Format {
            get {
                return ResourceManager.GetString("DatePicker_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ГГГГ.ММ.ДД.
        /// </summary>
        public static string Datepicker_Placeholder {
            get {
                return ResourceManager.GetString("Datepicker_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось авторизоваться через выбранного провайдера.&lt;br/&gt;Попробуйте еще раз, или обратитесь к администратору Bonsai..
        /// </summary>
        public static string Front_AuthFailed_Description {
            get {
                return ResourceManager.GetString("Front_AuthFailed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад на страницу авторизации.
        /// </summary>
        public static string Front_AuthFailed_GoBack {
            get {
                return ResourceManager.GetString("Front_AuthFailed_GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка авторизации.
        /// </summary>
        public static string Front_AuthFailed_Title {
            get {
                return ResourceManager.GetString("Front_AuthFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В этот день ничего не произошло..
        /// </summary>
        public static string Front_Calendar_NothingHappened {
            get {
                return ResourceManager.GetString("Front_Calendar_NothingHappened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пн, Вт, Ср, Чт, Пт, Сб, Вс.
        /// </summary>
        public static string Front_Calendar_WeekdaysShort {
            get {
                return ResourceManager.GetString("Front_Calendar_WeekdaysShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить страницу.
        /// </summary>
        public static string Front_Error_NotFound_AddPage {
            get {
                return ResourceManager.GetString("Front_Error_NotFound_AddPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увы и ах! Такая страница не существует. &lt;br/&gt;Возможно, она еще не создана, или вы перешли по ссылке с ошибкой..
        /// </summary>
        public static string Front_Error_NotFound_Description {
            get {
                return ResourceManager.GetString("Front_Error_NotFound_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка 404.
        /// </summary>
        public static string Front_Error_NotFound_Error {
            get {
                return ResourceManager.GetString("Front_Error_NotFound_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На главную.
        /// </summary>
        public static string Front_Error_NotFound_MainLink {
            get {
                return ResourceManager.GetString("Front_Error_NotFound_MainLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница не найдена.
        /// </summary>
        public static string Front_Error_NotFound_Title {
            get {
                return ResourceManager.GetString("Front_Error_NotFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестно.
        /// </summary>
        public static string Front_Facts_DeathDate_Unknown {
            get {
                return ResourceManager.GetString("Front_Facts_DeathDate_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Женский.
        /// </summary>
        public static string Front_Facts_Gender_Female {
            get {
                return ResourceManager.GetString("Front_Facts_Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мужской.
        /// </summary>
        public static string Front_Facts_Gender_Male {
            get {
                return ResourceManager.GetString("Front_Facts_Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2} {0} {1}.
        /// </summary>
        public static string Front_Facts_HumanName_FullFormat {
            get {
                return ResourceManager.GetString("Front_Facts_HumanName_FullFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилии.
        /// </summary>
        public static string Front_Facts_HumanName_LastNames {
            get {
                return ResourceManager.GetString("Front_Facts_HumanName_LastNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная страница.
        /// </summary>
        public static string Front_Home_Title {
            get {
                return ResourceManager.GetString("Front_Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новые медиа-файлы.
        /// </summary>
        public static string Front_Home_UpdatedMedia {
            get {
                return ResourceManager.GetString("Front_Home_UpdatedMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновленные страницы.
        /// </summary>
        public static string Front_Home_UpdatedPages {
            get {
                return ResourceManager.GetString("Front_Home_UpdatedPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При загрузке Bonsai произошла ошибка.&lt;br/&gt;Подробная информация записана в логи..
        /// </summary>
        public static string Front_Loading_Error {
            get {
                return ResourceManager.GetString("Front_Loading_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonsai загружается....
        /// </summary>
        public static string Front_Loading_InProgress1 {
            get {
                return ResourceManager.GetString("Front_Loading_InProgress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Откиньтесь на спинку кресла и отдохните - это займет не более минуты :).
        /// </summary>
        public static string Front_Loading_InProgress2 {
            get {
                return ResourceManager.GetString("Front_Loading_InProgress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка.
        /// </summary>
        public static string Front_Loading_Title {
            get {
                return ResourceManager.GetString("Front_Loading_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Демонстрационный аккаунт администратора:.
        /// </summary>
        public static string Front_Login_DemoAccount {
            get {
                return ResourceManager.GetString("Front_Login_DemoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Или введите логин и пароль, полученные от администратора:.
        /// </summary>
        public static string Front_Login_EnterPassword {
            get {
                return ResourceManager.GetString("Front_Login_EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход через {0}.
        /// </summary>
        public static string Front_Login_ExternalAuth {
            get {
                return ResourceManager.GetString("Front_Login_ExternalAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string Front_Login_Login {
            get {
                return ResourceManager.GetString("Front_Login_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница доступна только для зарегистрированных пользователей..
        /// </summary>
        public static string Front_Login_OnlyForRegistered {
            get {
                return ResourceManager.GetString("Front_Login_OnlyForRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Front_Login_Password {
            get {
                return ResourceManager.GetString("Front_Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход по логину и паролю.
        /// </summary>
        public static string Front_Login_PasswordAuth {
            get {
                return ResourceManager.GetString("Front_Login_PasswordAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, авторизуйтесь с помощью одного из доступных сервисов:.
        /// </summary>
        public static string Front_Login_PleaseAuthorize {
            get {
                return ResourceManager.GetString("Front_Login_PleaseAuthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы также можете &lt;a href=&quot;{0}&quot;&gt;зарегистрировать новую запись&lt;/a&gt;, или ввести логин и пароль, полученные от администратора:.
        /// </summary>
        public static string Front_Login_Register {
            get {
                return ResourceManager.GetString("Front_Login_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Ошибка:&lt;/b&gt; Не удалось авторизоваться.&lt;br /&gt;Возможно, вы ввели некорректный пароль? Попробуйте снова..
        /// </summary>
        public static string Front_Login_StatusFailed {
            get {
                return ResourceManager.GetString("Front_Login_StatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Ошибка:&lt;/b&gt;Ваша учетная запись заблокирована..
        /// </summary>
        public static string Front_Login_StatusLockedOut {
            get {
                return ResourceManager.GetString("Front_Login_StatusLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша учетная запись еще не была проверена администратором.&lt;br/&gt;Пожалуйста, дождитесь проверки - тогда вы сможете пользоваться системой..
        /// </summary>
        public static string Front_Login_StatusUnvalidated {
            get {
                return ResourceManager.GetString("Front_Login_StatusUnvalidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизация.
        /// </summary>
        public static string Front_Login_Title {
            get {
                return ResourceManager.GetString("Front_Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        public static string Front_Login_Username {
            get {
                return ResourceManager.GetString("Front_Login_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действия.
        /// </summary>
        public static string Front_Media_Actions {
            get {
                return ResourceManager.GetString("Front_Media_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string Front_Media_Date {
            get {
                return ResourceManager.GetString("Front_Media_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображены.
        /// </summary>
        public static string Front_Media_Depicted {
            get {
                return ResourceManager.GetString("Front_Media_Depicted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скачать.
        /// </summary>
        public static string Front_Media_Download {
            get {
                return ResourceManager.GetString("Front_Media_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string Front_Media_Edit {
            get {
                return ResourceManager.GetString("Front_Media_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Событие.
        /// </summary>
        public static string Front_Media_Event {
            get {
                return ResourceManager.GetString("Front_Media_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место.
        /// </summary>
        public static string Front_Media_Location {
            get {
                return ResourceManager.GetString("Front_Media_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оригинал.
        /// </summary>
        public static string Front_Media_Original {
            get {
                return ResourceManager.GetString("Front_Media_Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш браузер не поддерживает просмотр видео..
        /// </summary>
        public static string Front_Media_Video_BrowserUnsupported {
            get {
                return ResourceManager.GetString("Front_Media_Video_BrowserUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видео обрабатывается....
        /// </summary>
        public static string Front_Media_Video_Processing {
            get {
                return ResourceManager.GetString("Front_Media_Video_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видео будет доступно после обработки. Попробуйте перезагрузить страницу..
        /// </summary>
        public static string Front_Media_Video_TryRefreshing {
            get {
                return ResourceManager.GetString("Front_Media_Video_TryRefreshing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правки.
        /// </summary>
        public static string Front_Page_AdminLinks_Changes {
            get {
                return ResourceManager.GetString("Front_Page_AdminLinks_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Медиа.
        /// </summary>
        public static string Front_Page_AdminLinks_Media {
            get {
                return ResourceManager.GetString("Front_Page_AdminLinks_Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Связи.
        /// </summary>
        public static string Front_Page_AdminLinks_Relations {
            get {
                return ResourceManager.GetString("Front_Page_AdminLinks_Relations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст и факты.
        /// </summary>
        public static string Front_Page_AdminLinks_TextAndFacts {
            get {
                return ResourceManager.GetString("Front_Page_AdminLinks_TextAndFacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ничего не известно..
        /// </summary>
        public static string Front_Page_Description_Empty {
            get {
                return ResourceManager.GetString("Front_Page_Description_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата неизвестна.
        /// </summary>
        public static string Front_Page_Media_DateUnknown {
            get {
                return ResourceManager.GetString("Front_Page_Media_DateUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Медиа-файлов нет..
        /// </summary>
        public static string Front_Page_Media_Empty {
            get {
                return ResourceManager.GetString("Front_Page_Media_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Давно.
        /// </summary>
        public static string Front_Page_Media_LongAgo {
            get {
                return ResourceManager.GetString("Front_Page_Media_LongAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  — Медиа.
        /// </summary>
        public static string Front_Page_Media_Title {
            get {
                return ResourceManager.GetString("Front_Page_Media_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылок на данную страницу нет..
        /// </summary>
        public static string Front_Page_References_Empty {
            get {
                return ResourceManager.GetString("Front_Page_References_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На данную страницу ссылаются следующие страницы:.
        /// </summary>
        public static string Front_Page_References_Hint {
            get {
                return ResourceManager.GetString("Front_Page_References_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Front_Page_Tabs_Description {
            get {
                return ResourceManager.GetString("Front_Page_Tabs_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Медиа.
        /// </summary>
        public static string Front_Page_Tabs_Media {
            get {
                return ResourceManager.GetString("Front_Page_Tabs_Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылки.
        /// </summary>
        public static string Front_Page_Tabs_References {
            get {
                return ResourceManager.GetString("Front_Page_Tabs_References", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дерево.
        /// </summary>
        public static string Front_Page_Tabs_Tree {
            get {
                return ResourceManager.GetString("Front_Page_Tabs_Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во весь экран.
        /// </summary>
        public static string Front_Page_Tree_Fullscreen {
            get {
                return ResourceManager.GetString("Front_Page_Tree_Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В новом окне.
        /// </summary>
        public static string Front_Page_Tree_NewWindow {
            get {
                return ResourceManager.GetString("Front_Page_Tree_NewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} — Фамильное древо.
        /// </summary>
        public static string Front_Page_Tree_Title {
            get {
                return ResourceManager.GetString("Front_Page_Tree_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения.
        /// </summary>
        public static string Front_Register_Birthday {
            get {
                return ResourceManager.GetString("Front_Register_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать личную страницу.
        /// </summary>
        public static string Front_Register_CreatePersonalPage {
            get {
                return ResourceManager.GetString("Front_Register_CreatePersonalPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Front_Register_Email {
            get {
                return ResourceManager.GetString("Front_Register_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будет использоваться в качестве логина.
        /// </summary>
        public static string Front_Register_Email_Hint {
            get {
                return ResourceManager.GetString("Front_Register_Email_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Ошибка:&lt;/b&gt; пожалуйста, убедитесь, что вы заполнили все поля корректно и попробуйте снова..
        /// </summary>
        public static string Front_Register_Error {
            get {
                return ResourceManager.GetString("Front_Register_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string Front_Register_FirstName {
            get {
                return ResourceManager.GetString("Front_Register_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша учетная запись получит права администратора..
        /// </summary>
        public static string Front_Register_FirstUserHint {
            get {
                return ResourceManager.GetString("Front_Register_FirstUserHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверьте, что ввели актуальные данные - на русском языке и без ошибок. &lt;br/&gt;Учетная запись будет проверена администратором, после чего вы сможете авторизоваться и пользоваться системой..
        /// </summary>
        public static string Front_Register_Hint {
            get {
                return ResourceManager.GetString("Front_Register_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string Front_Register_LastName {
            get {
                return ResourceManager.GetString("Front_Register_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество.
        /// </summary>
        public static string Front_Register_MiddleName {
            get {
                return ResourceManager.GetString("Front_Register_MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опции.
        /// </summary>
        public static string Front_Register_Options {
            get {
                return ResourceManager.GetString("Front_Register_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Front_Register_Password {
            get {
                return ResourceManager.GetString("Front_Register_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимум 6 символов.
        /// </summary>
        public static string Front_Register_Password_Hint {
            get {
                return ResourceManager.GetString("Front_Register_Password_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повтор пароля.
        /// </summary>
        public static string Front_Register_Password_Repeat {
            get {
                return ResourceManager.GetString("Front_Register_Password_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Front_Register_Submit {
            get {
                return ResourceManager.GetString("Front_Register_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для создания учетной записи, пожалуйста, введите необходимую информацию..
        /// </summary>
        public static string Front_Register_Subtitle {
            get {
                return ResourceManager.GetString("Front_Register_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Front_Register_Title {
            get {
                return ResourceManager.GetString("Front_Register_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учетная запись не может быть создана, потому что регистрация новых пользователей запрещена администратором..
        /// </summary>
        public static string Front_RegisterDisabled_Description {
            get {
                return ResourceManager.GetString("Front_RegisterDisabled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация отклонена.
        /// </summary>
        public static string Front_RegisterDisabled_Title {
            get {
                return ResourceManager.GetString("Front_RegisterDisabled_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На главную страницу.
        /// </summary>
        public static string Front_RegisterSuccess_GoMain {
            get {
                return ResourceManager.GetString("Front_RegisterSuccess_GoMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша учетная запись будет проверена администратором, после чего вы сможете авторизоваться и пользоваться системой..
        /// </summary>
        public static string Front_RegisterSuccess_ReviewPending {
            get {
                return ResourceManager.GetString("Front_RegisterSuccess_ReviewPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы успешно зарегистрированы!.
        /// </summary>
        public static string Front_RegisterSuccess_Success {
            get {
                return ResourceManager.GetString("Front_RegisterSuccess_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Front_RegisterSuccess_Title {
            get {
                return ResourceManager.GetString("Front_RegisterSuccess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По вашему запросу ничего не найдено..
        /// </summary>
        public static string Front_Search_NothingFound {
            get {
                return ResourceManager.GetString("Front_Search_NothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрос слишком короткий. Введите как минимум три символа..
        /// </summary>
        public static string Front_Search_QueryTooShort {
            get {
                return ResourceManager.GetString("Front_Search_QueryTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результаты поиска.
        /// </summary>
        public static string Front_Search_Results {
            get {
                return ResourceManager.GetString("Front_Search_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        public static string Front_Search_Title {
            get {
                return ResourceManager.GetString("Front_Search_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить дерево..
        /// </summary>
        public static string Front_Tree_LoadFailed {
            get {
                return ResourceManager.GetString("Front_Tree_LoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка....
        /// </summary>
        public static string Front_Tree_Loading {
            get {
                return ResourceManager.GetString("Front_Tree_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} — Фамильное древо.
        /// </summary>
        public static string Front_Tree_Title {
            get {
                return ResourceManager.GetString("Front_Tree_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление.
        /// </summary>
        public static string Global_UserHeader_Administration {
            get {
                return ResourceManager.GetString("Global_UserHeader_Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string Global_UserHeader_Login {
            get {
                return ResourceManager.GetString("Global_UserHeader_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        public static string Global_UserHeader_Logout {
            get {
                return ResourceManager.GetString("Global_UserHeader_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница.
        /// </summary>
        public static string Global_UserHeader_Page {
            get {
                return ResourceManager.GetString("Global_UserHeader_Page", resourceCulture);
            }
        }
    }
}
